export const SECURITY_EVENT_RETENTION_DAYS = 90;
export const SESSION_ACTIVITY_UPDATE_THRESHOLD_MS = 5 * 60 * 1000; // 5 minutes
export const SUSPICIOUS_FAILED_LOGIN_THRESHOLD = 5;
export const SUSPICIOUS_UNIQUE_IP_THRESHOLD = 3;
export const SUSPICIOUS_RECENT_SESSION_THRESHOLD = 10;
export const SECURITY_AUDIT_MAX_RISK_SCORE = 100;

export const SECURITY_EVENT_DEFAULT_SUCCESS_RETENTION_DAYS = 30;
export const SECURITY_EVENT_DEFAULT_FAILURE_RETENTION_DAYS = 90;

export const TOKEN_BLACKLIST_FALLBACK_EXPIRY_MS = 24 * 60 * 60 * 1000; // 24 hours

